version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: clinica_fenix_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Cambiado el puerto externo
    volumes:
      - postgres_data_2:/var/lib/postgresql/data  # Cambiado el nombre del volume
      - ./migrations:/docker-entrypoint-initdb.d/migrations
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    command: 
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    networks:
      - app-network-2  # Cambiado el nombre de la red

volumes:
  postgres_data_2:  # Cambiado el nombre del volume

networks:
  app-network-2:  # Cambiado el nombre de la red
    driver: bridge